### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by htmlguy** [harryhaaren/openAV-Luppp#105]
I cannot find out how to do anything in luppp.
In the wiki, nowhere does it specify how to open the options/config menu (which I have seen in one of the openav screencasts), or, really, accomplish anything.

It would be useful if there was a guide for how to actually use this tool practically, because I haven't found any.

I'm not saying that luppp is bad, I've seen the screencasts and it looks like it works well, I just think it needs better documentation, because I can't for the life of me figure out how to use it.

Also, in one of the manual pages, it says to right-click on a track to do something, but it instead brings up a rename dialog.

**Comment by harryhaaren** [comment]
Hi @htmlguy,

Its true there's little documentation for Luppp - personally I don't have a need for it, and its not something I like spending time on, because I could code up new stuff instead...

That said, here's a mini tutorial: Top left LUPPP text *is* the menu button!

Right clicking a track will rename, right-click a *clip in a track* and you'll see the context menu. "Load" means load a loop, or a .wav loop sample to be more specific. 

Click a clip, and it'll start record/playing/stopping.

And you'll need to know how to work JACK for routing audio in / out of Luppp, but that's outside the scope of what Luppp does: [see the libre music production tutorial](http://libremusicproduction.com/articles/demystifying-jack-%E2%80%93-beginners-guide-getting-started-jack).

Cheers, -Harry

**Comment by htmlguy** [comment]
Thanks!
Okay, I think I've got it now.

**Comment by harryhaaren** [comment]
Theres some sample drum break loops here, they're tagged with how long they are (see the audio.cfg file) and so Luppp will time-stretch them properly automatically: https://github.com/harryhaaren/openAV-content
